# Generated by Django 5.1.3 on 2024-12-06 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapidtest', '0002_alter_category_options_remove_answer_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date',
        ),
    ]
