# Generated by Django 5.1.3 on 2024-12-08 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidtest', '0003_remove_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='rapidtest.testattempt'),
        ),
    ]
