# Generated by Django 5.1.3 on 2024-12-16 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidtest', '0005_test_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
